const data = {
    products: [
      {
        _id: '1',
        name: 'Sundress with shiny detail',
        category: 'Dress',
        image: '/images/dress1.jpg',
        price: 120.00,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur ipsum ab explicabo possimus, tenetur, veritatis quam porro vitae libero provident hic! Dolores error explicabo exercitationem facere adipisci est ipsa! Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe qui dolore perferendis facere ad cumque id culpa quasi necessitatibus similique accusamus, dolorum animi excepturi sed! Cupiditate laboriosam voluptate nihil velit?',
      },
      {
        _id: '2',
        name: 'Sundress with ruched front',
        category: 'Dress',
        image: '/images/dress2.jpg',
        price: 100.00,
        countInStock: 20,
        rating: 4.0,
        numReviews: 10,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur ipsum ab explicabo possimus, tenetur, veritatis quam porro vitae libero provident hic! Dolores error explicabo exercitationem facere adipisci est ipsa! Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe qui dolore perferendis facere ad cumque id culpa quasi necessitatibus similique accusamus, dolorum animi excepturi sed! Cupiditate laboriosam voluptate nihil velit?',
      },
      {
        _id: '3',
        name: 'Dress in pink ditsy floral',
        category: 'Dress',
        image: '/images/dress3.jpg',
        price: 220.00,
        countInStock: 0,
        rating: 4.8,
        numReviews: 17,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur ipsum ab explicabo possimus, tenetur, veritatis quam porro vitae libero provident hic! Dolores error explicabo exercitationem facere adipisci est ipsa! Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe qui dolore perferendis facere ad cumque id culpa quasi necessitatibus similique accusamus, dolorum animi excepturi sed! Cupiditate laboriosam voluptate nihil velit?',
      },
      {
        _id: '4',
        name: 'Dress in polka dot',
        category: 'Dress',
        image: '/images/dress4.jpg',
        price: 78.00,
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur ipsum ab explicabo possimus, tenetur, veritatis quam porro vitae libero provident hic! Dolores error explicabo exercitationem facere adipisci est ipsa! Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe qui dolore perferendis facere ad cumque id culpa quasi necessitatibus similique accusamus, dolorum animi excepturi sed! Cupiditate laboriosam voluptate nihil velit?',
      },
      {
        _id: '5',
        name: 'Mini dress in yellow polka dot',
        category: 'Dress',
        image: '/images/dress5.jpg',
        price: 65.00,
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur ipsum ab explicabo possimus, tenetur, veritatis quam porro vitae libero provident hic! Dolores error explicabo exercitationem facere adipisci est ipsa! Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe qui dolore perferendis facere ad cumque id culpa quasi necessitatibus similique accusamus, dolorum animi excepturi sed! Cupiditate laboriosam voluptate nihil velit?',
      },
      {
        _id: '6',
        name: 'Dress in blue and red spot',
        category: 'Dress',
        image: '/images/dress6.jpg',
        price: 139.00,
        countInStock: 12,
        rating: 4.5,
        numReviews: 15,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur ipsum ab explicabo possimus, tenetur, veritatis quam porro vitae libero provident hic! Dolores error explicabo exercitationem facere adipisci est ipsa! Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe qui dolore perferendis facere ad cumque id culpa quasi necessitatibus similique accusamus, dolorum animi excepturi sed! Cupiditate laboriosam voluptate nihil velit?',
      },
      {
        _id: '7',
        name: 'White Pants',
        category: 'Pants',
        image: '/images/p4.jpg',
        price: 150.00,
        countInStock: 8,
        rating: 3,
        numReviews: 19,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur ipsum ab explicabo possimus, tenetur, veritatis quam porro vitae libero provident hic! Dolores error explicabo exercitationem facere adipisci est ipsa! Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe qui dolore perferendis facere ad cumque id culpa quasi necessitatibus similique accusamus, dolorum animi excepturi sed! Cupiditate laboriosam voluptate nihil velit?',
      },
      {
        _id: '8',
        name: 'Olive Pants',
        category: 'Pants',
        image: '/images/p5.jpg',
        price: 145.00,
        countInStock: 13,
        rating: 3.5,
        numReviews: 16,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur ipsum ab explicabo possimus, tenetur, veritatis quam porro vitae libero provident hic! Dolores error explicabo exercitationem facere adipisci est ipsa! Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe qui dolore perferendis facere ad cumque id culpa quasi necessitatibus similique accusamus, dolorum animi excepturi sed! Cupiditate laboriosam voluptate nihil velit?',
      },
      {
        _id: '9',
        name: 'Gray Pants',
        category: 'Pants',
        image: '/images/p6.jpg',
        price: 165.00,
        countInStock: 11,
        rating: 4.5,
        numReviews: 12,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur ipsum ab explicabo possimus, tenetur, veritatis quam porro vitae libero provident hic! Dolores error explicabo exercitationem facere adipisci est ipsa! Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe qui dolore perferendis facere ad cumque id culpa quasi necessitatibus similique accusamus, dolorum animi excepturi sed! Cupiditate laboriosam voluptate nihil velit?',
      },
    ],
  };
  export default data;